---
- name: Apache HTTP Server Configuration File(s) Synchronization
  hosts: all
  become: yes

  tasks:
  ######## /etc/apache2/ports.conf
    - name: /etc/apache2/ports.conf
      copy:
        src: _etc/apache2/ports.conf
        dest: /etc/apache2/ports.conf
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /etc/apache2/ports.conf
      shell: |
          /usr/bin/md5sum /etc/apache2/ports.conf
      register: md5sum_output

    - name: Display md5sum /etc/apache2/ports.conf
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################


######## /etc/apache2/conf-available/api.conf
    - name: /etc/apache2/conf-available/api.conf
      copy:
        src: _etc/apache2/conf-available/api.conf
        dest: /etc/apache2/conf-available/api.conf
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /etc/apache2/conf-available/api.conf
      shell: |
          /usr/bin/md5sum /etc/apache2/conf-available/api.conf
      register: md5sum_output

    - name: Display md5sum /etc/apache2/conf-available/api.conf
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################


######## /etc/apache2/conf-available/base-view.conf
    - name: /etc/apache2/conf-available/base-view.conf
      copy:
        src: _etc/apache2/conf-available/base-view.conf
        dest: /etc/apache2/conf-available/base-view.conf
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /etc/apache2/conf-available/base-view.conf
      shell: |
          /usr/bin/md5sum /etc/apache2/conf-available/base-view.conf
      register: md5sum_output

    - name: Display md5sum /etc/apache2/conf-available/base-view.conf
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################


######## /etc/apache2/conf-available/userportal.conf
    - name: /etc/apache2/conf-available/userportal.conf
      copy:
        src: _etc/apache2/conf-available/userportal.conf
        dest: /etc/apache2/conf-available/userportal.conf
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /etc/apache2/conf-available/userportal.conf
      shell: |
          /usr/bin/md5sum /etc/apache2/conf-available/userportal.conf
      register: md5sum_output

    - name: Display md5sum /etc/apache2/conf-available/userportal.conf
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################


######## /etc/apache2/sites-available/000-default.conf
    - name: /etc/apache2/sites-available/000-default.conf
      copy:
        src: _etc/apache2/sites-available/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /etc/apache2/sites-available/000-default.conf
      shell: |
          /usr/bin/md5sum /etc/apache2/sites-available/000-default.conf
      register: md5sum_output

    - name: Display md5sum /etc/apache2/sites-available/000-default.conf
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################


######## /etc/apache2/sites-available/default-ssl.conf
    - name: /etc/apache2/sites-available/default-ssl.conf
      copy:
        src: _etc/apache2/sites-available/default-ssl.conf
        dest: /etc/apache2/sites-available/default-ssl.conf
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /etc/apache2/sites-available/default-ssl.conf
      shell: |
          /usr/bin/md5sum /etc/apache2/sites-available/default-ssl.conf
      register: md5sum_output

    - name: Display md5sum /etc/apache2/sites-available/default-ssl.conf
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################


######## /var/www/html/constants.php
    - name: /var/www/html/constants.php
      copy:
        src: _var/www/html/constants.php
        dest: /var/www/html/constants.php
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /var/www/html/constants.php
      shell: |
          /usr/bin/md5sum /var/www/html/constants.php
      register: md5sum_output

    - name: Display md5sum /var/www/html/constants.php
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################


###############################################################################
######## End of Configuration File(s) Synchronization
###############################################################################

    - name: Test and Reload Apache
      shell: |
        /usr/sbin/apache2ctl configtest && /usr/bin/systemctl reload apache2.service

