---
- name: Apache HTTP Server Configuration Files
  hosts: all
  become: yes
  
  tasks:
    - name: /etc/apache2/ports.conf
      copy:
        src: files/ports.conf
        dest: /etc/apache2/ports.conf
        owner: root
        group: root
        mode: '0644'

    - name: /etc/apache2/conf-available/api.conf
      copy:
        src: files/api.conf
        dest: /etc/apache2/conf-available/api.conf
        owner: root
        group: root
        mode: '0644'

    - name: /etc/apache2/conf-available/base-view.conf
      copy:
        src: files/base-view.conf
        dest: /etc/apache2/conf-available/base-view.conf
        owner: root
        group: root
        mode: '0644'

    - name: /etc/apache2/conf-available/userportal.conf
      copy:
        src: files/userportal.conf
        dest: /etc/apache2/conf-available/userportal.conf
        owner: root
        group: root
        mode: '0644'

    - name: /etc/apache2/sites-available/000-default.conf
      copy:
        src: files/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        owner: root
        group: root
        mode: '0644'

    - name: /etc/apache2/sites-available/default-ssl.conf
      copy:
        src: files/default-ssl.conf
        dest: /etc/apache2/sites-available/default-ssl.conf
        owner: root
        group: root
        mode: '0644'

    - name: md5sum /etc/apache2/sites-available/default-ssl.conf
      shell: |
          /usr/bin/md5sum /etc/apache2/sites-available/default-ssl.conf

    - name: Test and Reload Apache
      shell: |
        /usr/sbin/apache2ctl configtest && /usr/bin/systemctl reload apache2.service
