---
- name: Apache HTTP Server Configuration Synchronization
  hosts: all
  become: yes

  vars:
    apache2_configuration_files:
      - ports.conf
      - conf-available/api.conf
      - conf-available/base-view.conf
      - conf-available/userportal.conf
      - sites-available/000-default.conf
      - sites-available/default-ssl.conf

  tasks:
    - name: Synchronize Apache HTTP Server Configuration Files
      copy:
        # Implicitly Sourced FROM: ./files/ via Ansible Search Path
        # https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbook_pathing.html#config-paths
        # Maintains Directory Parity Between Source and Destination
        src: "etc/apache2/{{ item }}"
        dest: "/etc/apache2/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ apache2_configuration_files }}"

    - name: Test and Reload Apache
      shell: |
        /usr/sbin/apache2ctl configtest && /usr/bin/systemctl reload apache2.service

