---
- name: Shorewall Firewall Configuration Synchronization
  hosts: all
  become: yes

  vars:
    shorewall_configuration_files:
      - rules

  tasks:
    - name: Synchronize Shorewall Firewall Configuration Files
      copy:
        # Implicitly Sourced FROM: ./files/ via Ansible Search Path
        # https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbook_pathing.html#config-paths
        # Maintains Directory Parity Between Source and Destination
        src: "etc/shorewall/{{ item }}"
        dest: "/etc/shorewall/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ shorewall_configuration_files }}"


    - name: Test and Restart Shorewall Firewall
      shell: |
        /usr/sbin/shorewall check && systemctl restart shorewall.service

