---
- name: Sync Static Configs
  hosts: all
  become: yes  # Runs as sudo to write to /etc
  
  tasks:
    - name: Push ports.conf to Apache directory
      copy:
        src: files/ports.conf
        dest: /etc/apache2/ports.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
