---
- name: Apache HTTP Server Web Content Synchronization
  hosts: all
  become: yes

  tasks:
    - name: Web Content Synchronization
      ansible.builtin.copy:
        src: var/www/html/
        dest: /var/www/html/
        owner: "root"
        group: "root"
        mode: '0755'

