RewriteEngine on
RewriteRule ^/(base-view)/(.*)$ https://%{SERVER_NAME}/$1/$2 [R,L]
RewriteRule ^/(base-view)$ https://%{SERVER_NAME}/$1/ [R,L]

ProxyPreserveHost On
ProxyRequests Off
SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
ProxyPass /base-view/ https://127.0.0.1:8081/base-view/
ProxyPassReverse /base-view/ https://127.0.0.1:8081/base-view/
ProxyPass /json https://127.0.0.1:8081/json
ProxyPassReverse /json https://127.0.0.1:8081/json
ProxyPass /shell https://127.0.0.1:8081/shell
ProxyPassReverse /shell https://127.0.0.1:8081/shell
